spring:
  application:
    name: nanollm-gateway

server:
  port: 28080

logging:
  level:
    org.springframework.cloud: DEBUG

llm:
  provider:
  - type: dashscope
    model-prefix: dashscope
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    alias:
      xiaomi:
        - tongyi-xiaomi-analysis-pro
        - tongyi-xiaomi-analysis-flash
    apikey:
      - ${DASHSCOPE_API_KEY}
  - type: xiaomimimo
    model-prefix: xiaomimimo
    base-url: https://api.xiaomimimo.com/v1
    apikey:
      - ${MIMO_API_KEY}
  - type: deepseek
    model-prefix: deepseek
    base-url: https://api.deepseek.ai/v1
    apikey:
      - ${DEEPSEEK_API_KEY}